NXOS protocol param to standarized 'transport' param
napalm-automation/napalm-nxos pull request #94
Opened 2017-06-21 10:01 UTC by The-Loeki

Switch the optional argument `nxos_protocol` to the new, standarized `transport`

References:
* https://github.com/napalm-automation/napalm-ios/pull/159
* https://github.com/napalm-automation/napalm-ios/issues/132
* https://github.com/napalm-automation/napalm-eos/pull/167

2017-06-21 10:02 UTC, The-Loeki commented
@dbarrosop @mirceaulinic I've taken the liberty to update this driver as well if that's ok with you guys

2017-06-21 10:04 UTC, mirceaulinic approved these changes
I'm fine with that, as it does not replace the existing `nxos_protocol`, but ensures consistency across the API. Thanks @The-Loeki

2017-06-26 07:47 UTC, dbarrosop commented
Great!

2017-06-26 08:54 UTC, mirceaulinic commented on napalm_nxos/nxos.py
> +        self.transport = optional_args.get('transport', optional_args.get('nxos_protocol', 'http'))
Let's default to `https` please, as documented - solves https://github.com/napalm-automation/napalm-nxos/issues/36
Then we'll include this PR in a major release, 0.6.0.
Thanks!

2017-06-26 08:54 UTC, mirceaulinic requested changes
Please see inline comment

2017-06-27 10:12 UTC, mirceaulinic approved these changes
Thanks @The-Loeki

2017-06-27 10:12 UTC, merged